### ISSUE TITLE
Issue with extracting refactorings for specific commits

### ISSUE THREAD

**Issue by somak-chatterjee** [PyRef/PyRef#2]
Hello! I've been trying to use PyRef for looking into a specific commit for Apache airflow. I used the command `python3 main.py getrefs -r "[PATH_TO_REPOSITORY]" -c "[CommitHash]" -d "[Directory]` to fetch refactorings for Apache airflow. However I'm getting an error after executing the command. This is what the output in the terminal looks like: 

`python3 PyRef/main.py getrefs -r Repos/airflow/ -c "https://github.com/apache/airflow/pull/41985/commits/8382146f3e6296102f9b6db33f6e038a1a39d667"
Commit history already extracted, updating data.

Extracting Refs...
https://github.com/apache/airflow/pull/41985/commits/8382146f3e6296102f9b6db33f6e038a1a39d667
Traceback (most recent call last):
  File "/mnt/c/Stuff/Documents/Porashuna/Year2/Sem2/Thesis/Code/commit_analysis/PyRef/main.py", line 70, in <module>
    main()
  File "/mnt/c/Stuff/Documents/Porashuna/Year2/Sem2/Thesis/Code/commit_analysis/PyRef/main.py", line 66, in main
    options.func(options)
  File "/mnt/c/Stuff/Documents/Porashuna/Year2/Sem2/Thesis/Code/commit_analysis/PyRef/main.py", line 27, in extract_refs
    diff_list.extract_refs(args)
  File "/mnt/c/Stuff/Documents/Porashuna/Year2/Sem2/Thesis/Code/commit_analysis/PyRef/preprocessing/diff_list.py", line 136, in extract_refs
    build_diff_lists(repo_path + "/changes/", args.commit, args.directory, skip_time)
  File "/mnt/c/Stuff/Documents/Porashuna/Year2/Sem2/Thesis/Code/commit_analysis/PyRef/preprocessing/diff_list.py", line 58, in build_diff_lists
    df = pd.read_csv(changes_path + "/" + name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Stuff/Documents/Porashuna/Year2/Sem2/Thesis/Code/commit_analysis/commit_analysis/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Stuff/Documents/Porashuna/Year2/Sem2/Thesis/Code/commit_analysis/commit_analysis/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Stuff/Documents/Porashuna/Year2/Sem2/Thesis/Code/commit_analysis/commit_analysis/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Stuff/Documents/Porashuna/Year2/Sem2/Thesis/Code/commit_analysis/commit_analysis/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Stuff/Documents/Porashuna/Year2/Sem2/Thesis/Code/commit_analysis/commit_analysis/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Stuff/Documents/Porashuna/Year2/Sem2/Thesis/Code/commit_analysis/commit_analysis/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/mnt/c/Stuff/Documents/Porashuna/Year2/Sem2/Thesis/Code/commit_analysis/commit_analysis/lib/python3.11/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Repos/airflow//changes//https://github.com/apache/airflow/pull/41985/commits/8382146f3e6296102f9b6db33f6e038a1a39d667.csv'`

Any help would be appreciated. I'm new to using PyReF

**Comment by bin-lin** [comment]
Hi, the problem is that "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." PyRef is not able to find the commit in the airflow repo.

**Comment by somak-chatterjee** [comment]
Hi! Thanks for the explanation!
